### ISSUE TITLE
Causes Visual Editor to throw error in new version

### ISSUE THREAD

**Issue by kristiandelay** [MWStake/NewPageCSS#2]
When an article is using the <css> tag, the visual editor breaks when trying to edit.

Error:
```
error
: 
{code: "internal_api_error_Error",…}
code
: 
"internal_api_error_Error"
errorclass
: 
"Error"
info
: 
"[Y@@3XtVy8PMq4HdRik3OiwAAAAs] Exception caught: Call to a member function addHeadItem() on null"
trace
: 
"Error at extensions/NewPageCSS/src/CSSTag.php(20)\nfrom extensions/NewPageCSS/src/CSSTag.php(20)\n#0 includes/parser/Parser.php(4023): MWStake\\NewPageCSS\\CSSTag::handler(string, array, Parser, PPFrame_Hash)\n#1 includes/parser/PPFrame_Hash.php(354): Parser->extensionSubstitution(array, PPFrame_Hash, boolean)\n#2 includes/parser/Parser.php(2955): PPFrame_Hash->expand(PPNode_Hash_Tree, integer)\n#3 includes/parser/Parser.php(1610): Parser->replaceVariables(string)\n#4 includes/parser/Parser.php(882): Parser->internalParse(string, boolean, boolean)\n#5 includes/parser/Parser.php(931): Parser->recursiveTagParse(string)\n#6 includes/parser/Parsoid/Config/DataAccess.php(355): Parser->parseExtensionTagAsTopLevelDoc(string)\n#7 vendor/wikimedia/parsoid/src/Wt2Html/TT/ExtensionHandler.php(138): MediaWiki\\Parser\\Parsoid\\Config\\DataAccess->parseWikitext(MediaWiki\\Parser\\Parsoid\\Config\\PageConfig, ParserOutput, string)\n#8 vendor/wikimedia/parsoid/src/Wt2Html/TT/ExtensionHandler.php(279): Wikimedia\\Parsoid\\Wt2Html\\TT\\ExtensionHandler->onExtension(Wikimedia\\Parsoid\\Tokens\\SelfclosingTagTk)\n#9 vendor/wikimedia/parsoid/src/Wt2Html/TT/TokenHandler.php(150): Wikimedia\\Parsoid\\Wt2Html\\TT\\ExtensionHandler->onTag(Wikimedia\\Parsoid\\Tokens\\SelfclosingTagTk)\n#10 vendor/wikimedia/parsoid/src/Wt2Html/TokenTransformManager.php(132): Wikimedia\\Parsoid\\Wt2Html\\TT\\TokenHandler->process(array)\n#11 vendor/wikimedia/parsoid/src/Wt2Html/TokenTransformManager.php(185): Wikimedia\\Parsoid\\Wt2Html\\TokenTransformManager->processChunk(array)\n#12 vendor/wikimedia/parsoid/src/Wt2Html/ParserPipeline.php(140): Wikimedia\\Parsoid\\Wt2Html\\TokenTransformManager->process(array, array)\n#13 vendor/wikimedia/parsoid/src/Utils/PipelineUtils.php(106): Wikimedia\\Parsoid\\Wt2Html\\ParserPipeline->parse(string, array)\n#14 vendor/wikimedia/parsoid/src/Wt2Html/TT/TemplateHandler.php(617): Wikimedia\\Parsoid\\Utils\\PipelineUtils::processContentInPipeline(Wikimedia\\Parsoid\\Config\\Env, Wikimedia\\Parsoid\\Wt2Html\\PageConfigFrame, string, array)\n#15 vendor/wikimedia/parsoid/src/Wt2Html/TT/TemplateHandler.php(1121): Wikimedia\\Parsoid\\Wt2Html\\TT\\TemplateHandler->processTemplateSource(Wikimedia\\Parsoid\\Tokens\\SelfclosingTagTk, array, string)\n#16 vendor/wikimedia/parsoid/src/Wt2Html/TT/TemplateHandler.php(1151): Wikimedia\\Parsoid\\Wt2Html\\TT\\TemplateHandler->expandTemplate(Wikimedia\\Parsoid\\Wt2Html\\TT\\TemplateEncapsulator)\n#17 vendor/wikimedia/parsoid/src/Wt2Html/TT/TemplateHandler.php(1196): Wikimedia\\Parsoid\\Wt2Html\\TT\\TemplateHandler->onTemplate(Wikimedia\\Parsoid\\Tokens\\SelfclosingTagTk)\n#18 vendor/wikimedia/parsoid/src/Wt2Html/TT/TokenHandler.php(150): Wikimedia\\Parsoid\\Wt2Html\\TT\\TemplateHandler->onTag(Wikimedia\\Parsoid\\Tokens\\SelfclosingTagTk)\n#19 vendor/wikimedia/parsoid/src/Wt2Html/TokenTransformManager.php(132): Wikimedia\\Parsoid\\Wt2Html\\TT\\TokenHandler->process(array)\n#20 vendor/wikimedia/parsoid/src/Wt2Html/TokenTransformManager.php(195): Wikimedia\\Parsoid\\Wt2Html\\TokenTransformManager->processChunk(array)\n#21 vendor/wikimedia/parsoid/src/Wt2Html/TokenTransformManager.php(193): Wikimedia\\Parsoid\\Wt2Html\\TokenTransformManager->processChunkily(string, array)\n#22 vendor/wikimedia/parsoid/src/Wt2Html/TreeBuilder/TreeBuilderStage.php(487): Wikimedia\\Parsoid\\Wt2Html\\TokenTransformManager->processChunkily(string, array)\n#23 [internal function]: Wikimedia\\Parsoid\\Wt2Html\\TreeBuilder\\TreeBuilderStage->processChunkily(string, array)\n#24 vendor/wikimedia/parsoid/src/Wt2Html/DOMPostProcessor.php(904): Generator->current()\n#25 vendor/wikimedia/parsoid/src/Wt2Html/ParserPipeline.php(180): Wikimedia\\Parsoid\\Wt2Html\\DOMPostProcessor->processChunkily(string, array)\n#26 vendor/wikimedia/parsoid/src/Wt2Html/ParserPipelineFactory.php(308): Wikimedia\\Parsoid\\Wt2Html\\ParserPipeline->parseChunkily(string, array)\n#27 vendor/wikimedia/parsoid/src/Wikitext/ContentModelHandler.php(123): Wikimedia\\Parsoid\\Wt2Html\\ParserPipelineFactory->parse(string)\n#28 vendor/wikimedia/parsoid/src/Parsoid.php(172): Wikimedia\\Parsoid\\Wikitext\\ContentModelHandler->toDOM(Wikimedia\\Parsoid\\Ext\\ParsoidExtensionAPI)\n#29 vendor/wikimedia/parsoid/src/Parsoid.php(210): Wikimedia\\Parsoid\\Parsoid->parseWikitext(MediaWiki\\Parser\\Parsoid\\Config\\PageConfig, ParserOutput, array)\n#30 extensions/VisualEditor/includes/VisualEditorParsoidClient.php(123): Wikimedia\\Parsoid\\Parsoid->wikitext2html(MediaWiki\\Parser\\Parsoid\\Config\\PageConfig, array, NULL, ParserOutput)\n#31 extensions/VisualEditor/includes/ParsoidHelper.php(224): MediaWiki\\Extension\\VisualEditor\\VisualEditorParsoidClient->getPageHtml(MediaWiki\\Revision\\RevisionStoreRecord, LanguageEn)\n#32 extensions/VisualEditor/includes/ApiParsoidTrait.php(134): MediaWiki\\Extension\\VisualEditor\\ParsoidHelper->requestRestbasePageHtml(MediaWiki\\Revision\\RevisionStoreRecord, LanguageEn)\n#33 extensions/VisualEditor/includes/ApiVisualEditor.php(279): MediaWiki\\Extension\\VisualEditor\\ApiVisualEditor->requestRestbasePageHtml(MediaWiki\\Revision\\RevisionStoreRecord)\n#34 includes/api/ApiMain.php(1900): MediaWiki\\Extension\\VisualEditor\\ApiVisualEditor->execute()\n#35 includes/api/ApiMain.php(875): ApiMain->executeAction()\n#36 includes/api/ApiMain.php(846): ApiMain->executeActionWithErrorHandling()\n#37 api.php(90): ApiMain->execute()\n#38 api.php(45): wfApiMain()\n#39 {main}"
```

Versions:
`

MediaWiki | 1.39.1
-- | --
PHP | 7.4.33 (apache2handler)
MariaDB | 10.1.45-MariaDB
ICU | 71.1
Lua | 5.1.5
Pygments | 2.11.2
Elasticsearch | 7.10.2

[MediaWiki](https://www.mediawiki.org/)	1.39.1
[PHP](https://php.net/)	7.4.33 (apache2handler)
[MariaDB](https://mariadb.org/)	10.1.45-MariaDB
[ICU](https://icu.unicode.org/)	71.1
[Lua](http://www.lua.org/)	5.1.5
[Pygments](https://pygments.org/)	2.11.2
[Elasticsearch](https://www.elastic.co/elasticsearch)	7.10.2`

**Comment by kristiandelay** [comment]
**FIX**:
parser was undefined when using MediawikiServices to get parser. instead we should update the hook defintion to pass in parser paramater

```
<?php

namespace MWStake\NewPageCSS;

use MediaWiki\MediaWikiServices;
use Sanitizer;

class CSSTag {

	/**
	 * Handle the css tag
	 *
	 * @param string $content of the css tag
	 * @return string empty
	 */
	public static function handler( $content, $params, $parser, $frame ): string {
		// $parser = MediaWikiServices::getInstance()->getParser();

		$css = htmlspecialchars( trim( Sanitizer::checkCss( $content ) ) );
		$parser->getOutput()->addHeadItem(
			<<<EOT
<style type="text/css">
/*<![CDATA[*/
{$css}
/*]]>*/
</style>
EOT
		);
		return '';
	}
}

```

**Comment by hexmode** [comment]
Could you try out the fix and reopen this issue if it doesn't work?
